export interface Product {
    id: string;
    category: string;
    name: string;
    image: string;
}

export interface CategoryTitle {
    [key: string]: string;
}

export type ProductsByCategory = Record<string, Product[]>;

export const productsByCategory: ProductsByCategory = {
  'cooking-oil': [
    {
      id: 'fresh-fri',
      category: 'cooking-oil',
      name: 'Vegetable Cooking Oil',
      image: '/images/products/cooking-oil/FreshFri.png',
    },
    {
      id: 'salit',
      category: 'cooking-oil',
      name: 'Vegetable Cooking Oil',
      image: '/images/products/cooking-oil/Salit.jpeg',
    },
    {
      id: 'popco',
      category: 'cooking-oil',
      name: 'Fortified Vegetable Oil',
      image: '/images/products/cooking-oil/Popco.png',
    },
    {
      id: 'mpishi-poa',
      category: 'cooking-oil',
      name: 'Vegetable Cooking Fat',
      image: '/images/products/cooking-oil/MpishiPoa.png',
    },
    {
      id: 'fry-mate',
      category: 'cooking-oil',
      name: 'Vegetable Cooking Fat',
      image: '/images/products/cooking-oil/FryMate.png',
    },
    {
      id: 'pure-mountain-canola-oil',
      category: 'cooking-oil',
      name: 'Canola Oil',
      image: '/images/products/cooking-oil/Canola.jpg',
    },
    {
      id: 'pure-mountain-megafry',
      category: 'cooking-oil',
      name: 'Mega Fry',
      image: '/images/products/cooking-oil/Megafry.webp',
    },
  ],
  'soaps-self-care': [
    {
      id: 'detrex-aloe-vera',
      category: 'soaps-self-care',
      name: 'Aloe Vera Soap',
      image: '/images/products/soaps/Detrex-AloeVera.webp',
    },
    {
      id: 'detrex-cool-mint',
      category: 'soaps-self-care',
      name: 'Cool Mint Soap',
      image: '/images/products/soaps/Detrex-CoolMint.webp',
    },
    {
      id: 'detrex-citronella',
      category: 'soaps-self-care',
      name: 'Citronella Oil Soap',
      image: '/images/products/soaps/Detrex-CitronellaOil.webp',
    },
    {
      id: 'detrex-pine-drops',
      category: 'soaps-self-care',
      name: 'Pine Drops Soap',
      image: '/images/products/soaps/Detrex-PineDrops.webp',
    },
    {
      id: 'sawa-rose',
      category: 'soaps-self-care',
      name: 'Rose Soap',
      image: '/images/products/soaps/Sawa-Rose.png',
    },
    {
      id: 'sawa-orignal',
      category: 'soaps-self-care',
      name: 'Original Soap',
      image: '/images/products/soaps/Sawa-Original.png',
    },
    {
      id: 'sawa-herbal',
      category: 'soaps-self-care',
      name: 'Herbal Soap',
      image: '/images/products/soaps/Sawa-Herbal.png',
    },
    {
      id: 'sawa-strawberry',
      category: 'soaps-self-care',
      name: 'Strawberry Soap',
      image: '/images/products/soaps/Sawa-Strawberry.png',
    },
    {
      id: 'sawa-lemon-honey',
      category: 'soaps-self-care',
      name: 'Lemon Honey Soap',
      image: '/images/products/soaps/Sawa-Lemon-Honey.png',
    },
    {
      id: 'sawa-chocolate',
      category: 'soaps-self-care',
      name: 'Chocolate Soap',
      image: '/images/products/soaps/Sawa-Chocolate.png',
    },
    {
      id: 'sawa-bubblegum',
      category: 'soaps-self-care',
      name: 'Bubblegum Soap',
      image: '/images/products/soaps/Sawa-Bubblegum.png',
    },
    {
      id: 'sawa-berry-splash',
      category: 'soaps-self-care',
      name: 'Berry Splash Body Wash',
      image: '/images/products/soaps/Sawa-Berry-Splash.png',
    },
    {
      id: 'sawa-aloe-splash',
      category: 'soaps-self-care',
      name: 'Aloe Splash Body Wash',
      image: '/images/products/soaps/Sawa-Aloe-Splash.png',
    },
    {
      id: 'sawa-original-splash',
      category: 'soaps-self-care',
      name: 'Original Splash Body Wash',
      image: '/images/products/soaps/Sawa-Original-Splash.png',
    },
    {
      id: 'sawa-strawberry-handwash',
      category: 'soaps-self-care',
      name: 'Strawberry Handwash',
      image: '/images/products/soaps/Sawa-Strawberry-Handwash.png',
    },
    {
      id: 'sawa-aloe-vera-handwash',
      category: 'soaps-self-care',
      name: 'Aloe Vera Handwash',
      image: '/images/products/soaps/Sawa-Aloe-Vera-Handwash.png',
    },
    {
      id: 'sawa-original-handwash',
      category: 'soaps-self-care',
      name: 'Original Handwash',
      image: '/images/products/soaps/Sawa-Original-Handwash.png',
    },
    {
      id: 'diva-milky-nuts',
      category: 'soaps-self-care',
      name: 'Milky Nuts Soap',
      image: '/images/products/soaps/Diva-Milky-Nuts.png',
    },
    {
      id: 'diva-sunshine-fruit',
      category: 'soaps-self-care',
      name: 'Sunshine Fruit Soap',
      image: '/images/products/soaps/Diva-Sunshine-Fruit.png',
    },
    {
      id: 'diva-olive-n-tulip',
      category: 'soaps-self-care',
      name: 'Olive n Tulip Soap',
      image: '/images/products/soaps/Diva-Olive-n-Tulip.png',
    },
    {
      id: 'diva-mango-temptation',
      category: 'soaps-self-care',
      name: 'Mango Temptation Soap',
      image: '/images/products/soaps/Diva-Mango-Temptation.png',
    },
    {
      id: 'diva-citrus-n-cream',
      category: 'soaps-self-care',
      name: 'Citrus n Cream Soap',
      image: '/images/products/soaps/Diva-Citrus-n-Cream.png',
    },
    {
      id: 'diva-aloe-vera',
      category: 'soaps-self-care',
      name: 'Aloe Vera Soap',
      image: '/images/products/soaps/Diva-Aloe-Vera.png',
    },
    {
      id: 'afrisense-skin-toning-bathing-bar',
      category: 'soaps-self-care',
      name: 'Skin Toning Bathing Bar',
      image: '/images/products/soaps/Afrisense-Skin-Toning-Bathing-Bar.png',
    },
    {
      id: 'afrisense-cleansing-&-moisturizing-bar',
      category: 'soaps-self-care',
      name: 'Cleansing & Moisturizing Bar',
      image: '/images/products/soaps/Afrisense-Cleansing-&-Moisturizing-Bar.png',
    },
    {
      id: 'afrisense-nourishing-&-hydrating-bar',
      category: 'soaps-self-care',
      name: 'Nourishing & Hydrating Bar',
      image: '/images/products/soaps/Afrisense-Nourishing-&-Hydrating-Bar.png',
    },
  ],
  'wash-day-soaps': [
    {
      id: 'whitewash-white',
      category: 'wash-day-soaps',
      name: 'White - Brilliant for all purposes',
      image: '/images/products/soaps/Whitewash-White.png',
    },
    {
      id: 'whitewash-blue',
      category: 'wash-day-soaps',
      name: 'Blue - Colour Retainer',
      image: '/images/products/soaps/Whitewash-Blue.png',
    },
    {
      id: 'whitewash-green',
      category: 'wash-day-soaps',
      name: 'Green - Antiseptic',
      image: '/images/products/soaps/Whitewash-Green.png',
    },
    {
      id: 'whitewash-cream',
      category: 'wash-day-soaps',
      name: 'Cream - Gentle Multipurpose',
      image: '/images/products/soaps/Whitewash-Cream.png',
    },
    {
      id: 'whitewash-pink',
      category: 'wash-day-soaps',
      name: 'Pink - Pure sensations',
      image: '/images/products/soaps/Whitewash-Pink.png',
    },
    {
      id: 'whitewash-bar',
      category: 'wash-day-soaps',
      name: 'Bar Soaps',
      image: '/images/products/soaps/Whitewash-Bar.png',
    },
    {
        id: 'ushindi-blue',
        category: 'wash-day-soaps',
        name: 'Blue Multi-Purpose Stain Remover',
        image: '/images/products/soaps/Ushindi-Blue.png',
    },
    {
        id: 'ushindi-yellow',
        category: 'wash-day-soaps',
        name: 'Yellow Lemon Fragrance',
        image: '/images/products/soaps/Ushindi-Yellow.png',
    },
    {
        id: 'ushindi-white',
        category: 'wash-day-soaps',
        name: 'White With Glycerin',
        image: '/images/products/soaps/Ushindi-White.png',
    },
    {
        id: 'ushindi-green-antiseptic-plus',
        category: 'wash-day-soaps',
        name: 'Green Antiseptic Plus',
        image: '/images/products/soaps/Ushindi-Green.png',
    },
    {
        id: 'ushindi-cream',
        category: 'wash-day-soaps',
        name: 'Cream',
        image: '/images/products/soaps/Ushindi-Cream.png',
    },
    {
        id: 'ushindi-bar-soap',
        category: 'wash-day-soaps',
        name: 'Cream Bar Soap',
        image: '/images/products/soaps/Ushindi-Cream-Bar.png',
    },
    {
        id: 'ushindi-washing-powder',
        category: 'wash-day-soaps',
        name: 'Washing-Powder',
        image: '/images/products/soaps/Ushindi-Washing-Powder.png',
    },
    {
        id: 'ushindi-orange-dish-washing-liquid',
        category: 'wash-day-soaps',
        name: 'Orange Dish Washing Liquid',
        image: '/images/products/soaps/Ushindi-Orange-DWL.png',
    },
    {
        id: 'ushindi-lemon-dish-washing-liquid',
        category: 'wash-day-soaps',
        name: 'Lemon Dish Washing Liquid',
        image: '/images/products/soaps/Ushindi-Lemon-DWL.png',
    },
    {
        id: 'ushindi-orange-dish-washing-paste',
        category: 'wash-day-soaps',
        name: 'Orange Dish Washing Paste',
        image: '/images/products/soaps/Ushindi-Orange-DWP.png',
    },
    {
        id: 'ushindi-lemon-dish-washing-paste',
        category: 'wash-day-soaps',
        name: 'Lemon Dish Washing Paste',
        image: '/images/products/soaps/Ushindi-Lemon-DWP.png',
    },
    {
        id: 'ushindi-multi-floor-cleaner',
        category: 'wash-day-soaps',
        name: 'Multi-Floor Cleaner',
        image: '/images/products/soaps/Ushindi-Multi-Floor-Cleaner.png',
    },
    {
        id: 'ushindi-mfc-jerrican',
        category: 'wash-day-soaps',
        name: 'Multi-Floor Cleaner Jerrican',
        image: '/images/products/soaps/Ushindi-MFC-Jerrican.png',
    },
    {
        id: 'ndume-white-laundry-soap',
        category: 'wash-day-soaps',
        name: 'White Laundry Soap',
        image: '/images/products/soaps/Ndume-White-Laundry-Soap.png',
    },
    {
        id: 'nudume-cream-laundry-soap',
        category: 'wash-day-soaps',
        name: 'Cream Laundry Soap',
        image: '/images/products/soaps/Ndume-Cream-Laundry-Soap.png',
    },
    {
        id: 'nudume-herbal-laundry-soap',
        category: 'wash-day-soaps',
        name: 'Herbal Laundry Soap',
        image: '/images/products/soaps/Ndume-Herbal-Laundry-Soap.png',
    },
  ],
  'sauces': [
    {
        id: 'zesta-tomato-sauce',
        category: 'sauces',
        name: 'Tomato Sauce',
        image: '/images/products/sauces/Zesta-Tomato-Sauce.png',
    },
    {
        id: 'zesta-chilli-sauce',
        category: 'sauces',
        name: 'Chilli Sauce',
        image: '/images/products/sauces/Zesta-Chilli-Sauce.png',
    },
    {
        id: 'zesta-hot-sweet-sauce',
        category: 'sauces',
        name: 'Hot & Sweet Sauce',
        image: '/images/products/sauces/Zesta-Hot-&-Sweet-Sauce.png',
    },
    {
        id: 'zesta-tomato-ketchup',
        category: 'sauces',
        name: 'Tomato Ketchup',
        image: '/images/products/sauces/Zesta-Tomato-Ketchup.png',
    },
    {
        id: 'zesta-choma-sauce',
        category: 'sauces',
        name: 'Choma Sauce',
        image: '/images/products/sauces/Zesta-Choma-Sauce.png',
    },
    {
        id: 'zesta-tomato-garlic-sauce',
        category: 'sauces',
        name: 'Tomato Garlic Sauce',
        image: '/images/products/sauces/Zesta-Tomato-Garlic-Sauce.png',
    },
    {
        id: 'zesta-chilli-garlic-sauce',
        category: 'sauces',
        name: 'Chilli Garlic Sauce',
        image: '/images/products/sauces/Zesta-Chilli-Garlic-Sauce.png',
    },
    {
        id: 'zesta-mayonnaise',
        category: 'sauces',
        name: 'Mayonnaise',
        image: '/images/products/sauces/Zesta-Mayonnaise.png',
    },
    {
        id: 'zesta-mayocue',
        category: 'sauces',
        name: 'Mayocue',
        image: '/images/products/sauces/Zesta-Mayocue-Sauce.png',
    },
    {
        id: 'zesta-yellow-mustard',
        category: 'sauces',
        name: 'Yellow Mustard',
        image: '/images/products/sauces/Zesta-Yellow-Mustard.png',
    },
    {
        id: 'zesta-chilli-tamarind-sauce',
        category: 'sauces',
        name: 'Chilli Tamarind Sauce',
        image: '/images/products/sauces/Zesta-Chilli-Tamarind-Sauce.png',
    },
    {
        id: 'zesta-fruit-spicy-sauce',
        category: 'sauces',
        name: 'Fruit Spicy Sauce',
        image: '/images/products/sauces/Zesta-Fruit-Spicy-Sauce.png',
    },
    {
        id: 'zesta-mango-chutney',
        category: 'sauces',
        name: 'Mango Chutney',
        image: '/images/products/sauces/Zesta-Mango-Chutney.png',
    },
    {
        id: 'zesta-fruit-chutney',
        category: 'sauces',
        name: 'Fruit Chutney',
        image: '/images/products/sauces/Zesta-Fruit-Chutney.png',
    },
  ],
  'condiments': [
    {
        id: 'zesta-gravy-browning',
        category: 'condiments',
        name: 'Gravy Browning',
        image: '/images/products/condiments/Zesta-Gravy-Browning.png',
    },
    {
        id: 'zesta-soy-sauce',
        category: 'condiments',
        name: 'Soy Sauce',
        image: '/images/products/condiments/Zesta-Soy-Sauce.png',
    },
    {
        id: 'zesta-vanilla-essence',
        category: 'condiments',
        name: 'Vanilla Essence',
        image: '/images/products/condiments/Zesta-Vanilla-Essence.png',
    },
  ],
  'powders': [
    {
        id: 'zesta-baking-powder',
        category: 'powders',
        name: 'Baking Powder',
        image: '/images/products/powders/Zesta-Baking-Powder.png',
    },
    {
        id: 'bi-carbonate-soda',
        category: 'powders',
        name: 'Bi Carbonate Soda',
        image: '/images/products/powders/Zesta-Bi-Carbonate-Soda.png',
    },
    {
        id: 'caster-sugar',
        category: 'powders',
        name: 'Caster Sugar',
        image: '/images/products/powders/Zesta-Caster-Sugar.png',
    },
    {
        id: 'corn-flour',
        category: 'powders',
        name: 'Corn Flour',
        image: '/images/products/powders/Zesta-Corn-Flour.png',
    },
    {
        id: 'custard-powder',
        category: 'powders',
        name: 'Custard Powder',
        image: '/images/products/powders/Zesta-Custard-Powder.png',
    },
    {
        id: 'icing-sugar',
        category: 'powders',
        name: 'Icing Sugar',
        image: '/images/products/powders/Zesta-Icing-Sugar.png',
    },
  ],
  'vinegar': [
    {
        id: 'zesta-white-vinegar',
        category: 'vinegar',
        name: 'White Vinegar',
        image: '/images/products/vinegar/Zesta-White-Vinegar.png',
    },
    {
        id: 'zesta-brown-vinegar',
        category: 'vinegar',
        name: 'Brown Vinegar',
        image: '/images/products/vinegar/Zesta-Brown-Vinegar.png',
    },
  ],
  'jams': [
    {
        id: 'zesta-gooseberry-jam',
        category: 'jams',
        name: 'Gooseberry Jam',
        image: '/images/products/jams/Zesta-Gooseberry-Jam.png',
    },
    {
        id: 'zesta-raspberry-jam',
        category: 'jams',
        name: 'Raspberry Jam',
        image: '/images/products/jams/Zesta-Raspberry-Jam.png',
    },
    {
        id: 'zesta-very-berry-jam',
        category: 'jams',
        name: 'Very Berry Jam',
        image: '/images/products/jams/Zesta-Very-Berry-Jam.png',
    },
    {
        id: 'zesta-apricot-jam',
      category: 'jams',
      name: 'Apricot Jam',
      image: '/images/products/jams/Zesta-Apricot-Jam.png',
    },
    {
        id: 'zesta-mango-jam',
        category: 'jams',
        name: 'Mango Jam',
        image: '/images/products/jams/Zesta-Mango-Jam.png',
    },
    {
        id: 'zesta-mixed-fruit-jam',
        category: 'jams',
        name: 'Mixed Fruit Jam',
        image: '/images/products/jams/Zesta-Mixed-Fruit-Jam.png',
    },
    {
        id: 'zesta-orange-marmalade-jam',
        category: 'jams',
        name: 'Orange Marmalade Jam',
        image: '/images/products/jams/Zesta-Orange-Marmalade-Jam.png',
    },
    {
        id: 'zesta-pineapple-jam',
        category: 'jams',
        name: 'Pineapple Jam',
        image: '/images/products/jams/Zesta-Pineapple-Jam.png',
    },
    {
        id: 'zesta-red-plum-jam',
        category: 'jams',
        name: 'Red Plum Jam',
        image: '/images/products/jams/Zesta-Red-Plum-Jam.png',
    },
    {
        id: 'zesta-strawberry-jam',
        category: 'jams',
        name: 'Strawberry Jam',
        image: '/images/products/jams/Zesta-Strawberry-Jam.png',
    },
  ],
  'canned-food': [
    {
      id: 'kenylon-beans-in-tomato-sauce',
      category: 'canned-food',
      name: 'Beans in Tomato Sauce',
      image: '/images/products/canned-food/Beans-in-Tomato-Sauce.png',
    },
    {
      id: 'kenylon-butter-beans',
      category: 'canned-food',
      name: 'Butter Beans',
      image: '/images/products/canned-food/Butter-Beans.png',
    },
    {
      id: 'kenylon-chick-peas',
      category: 'canned-food',
      name: 'Chick Peas',
      image: '/images/products/canned-food/Chick-Peas.png',
    },
    {
      id: 'kenylon-corn-off-the-cob',
      category: 'canned-food',
      name: 'Corn Off the Cob',
      image: '/images/products/canned-food/Corn-Off-the-Cob.png',
    },
    {
      id: 'kenylon-crushed-tomatoes',
      category: 'canned-food',
      name: 'Crushed Tomatoes',
      image: '/images/products/canned-food/Crushed-tomatoes.png',
    },
    {
      id: 'kenylon-garden-peas',
      category: 'canned-food',
      name: 'Garden Peas',
      image: '/images/products/canned-food/Garden-Peas.png',
    },
    {
      id: 'kenylon-githeri',
      category: 'canned-food',
      name: 'Githeri',
      image: '/images/products/canned-food/Githeri.png',
    },
    {
      id: 'kenylon-processed-peas',
      category: 'canned-food',
      name: 'Processed Peas',
      image: '/images/products/canned-food/Processed-Peas.png',
    },
    {
      id: 'kenylon-whole-peeled-tomatoes',
      category: 'canned-food',
      name: 'Whole Peeled Tomatoes',
      image: '/images/products/canned-food/Whole-Peeled-Tomatoes.png',
    },
  ],
  'choco-drinks': [
    {
      id: 'choco-primio',
      category: 'choco-drinks',
      name: 'Choco Primio',
      image: '/images/products/choco-drinks/Choco-Primio.png',
    },
    {
      id: 'cocoa-primo',
      category: 'choco-drinks',
      name: 'Cocoa Primo',
      image: '/images/products/choco-drinks/Cocoa-Primo.png',
    },
    {
      id: 'choco-burst',
      category: 'choco-drinks',
      name: 'Choco Burst',
      image: '/images/products/choco-drinks/Choco-Burst.png',
    },
    {
      id: 'raha-drinking-chocolate',
      category: 'choco-drinks',
      name: 'Drinking Chocolate',
      image: '/images/products/choco-drinks/Raha-Drinking-Chocolate.webp',
    },
    {
      id: 'raha-cocoa',
      category: 'choco-drinks',
      name: 'Cocoa',
      image: '/images/products/choco-drinks/Raha-Cocoa.webp',
    },
  ],
  'rice': [
    {
      id: 'basmati-rice',
      category: 'rice',
      name: 'Basmati Rice',
      image: '/images/products/rice/Basmati.png',
    },
    {
      id: 'biryani-rice',
      category: 'rice',
      name: 'Biryani Rice',
      image: '/images/products/rice/Biryani.png',
    },
    {
      id: 'pishori-rice',
      category: 'rice',
      name: 'Pishori Rice',
      image: '/images/products/rice/Pishori.png',
    },
  ],
  'sweets': [
    {
      id: 'tropical-mints',
      category: 'sweets',
      name: 'Tropical Mints',
      image: '/images/products/sweets/Tropical-Mints.png',
    },
    {
      id: 'white-mints',
      category: 'sweets',
      name: 'White Mints',
      image: '/images/products/sweets/White-Mints.png',
    },
    {
      id: 'cough-drops',
      category: 'sweets',
      name: 'Cough Drops',
      image: '/images/products/sweets/Cough-Drops.png',
    },
    {
      id: 'ok-fruit-drops',
      category: 'sweets',
      name: 'OK Fruit Drops',
      image: '/images/products/sweets/OK-Fruit-Drops.png',
    },
    {
      id: 'orange-fruit-drops',
      category: 'sweets',
      name: 'Orange Fruit Drops',
      image: '/images/products/sweets/Orange-Fruit-Drops.png',
    },
  ],
  'drinks': [
    {
      id: 'water',
      category: 'drinks',
      name: 'Water',
      image: '/images/products/drinks/Water.webp',
    },
    {
      id: 'orange-cordial',
      category: 'drinks',
      name: 'Orange Cordial',
      image: '/images/products/drinks/Orange-Cordial.webp',
    },
    {
      id: 'mango-cordial',
      category: 'drinks',
      name: 'Mango Cordial',
      image: '/images/products/drinks/Mango-Cordial.webp',
    },
    {
      id: 'tropical-cordial',
      category: 'drinks',
      name: 'Tropical Cordial',
      image: '/images/products/drinks/Tropical-Cordial.webp',
    },
    {
      id: 'pineapple-cordial',
      category: 'drinks',
      name: 'Pineapple Cordial',
      image: '/images/products/drinks/Pineapple-Cordial.webp',
    },
    {
      id: 'cola',
      category: 'drinks',
      name: 'Cola',
      image: '/images/products/drinks/Cola.webp',
    },
    {
      id: 'orange',
      category: 'drinks',
      name: 'Orange',
      image: '/images/products/drinks/Orange.webp',
    },
    {
      id: 'tangawizi',
      category: 'drinks',
      name: 'Tangawizi',
      image: '/images/products/drinks/Tangawizi.webp',
    },
    {
      id: 'lemonade-bountyful',
      category: 'drinks',
      name: 'Lemonade',
      image: '/images/products/drinks/Lemonaid.png',
    },
    {
      id: 'lemon-lime',
      category: 'drinks',
      name: 'Lemon Lime',
      image: '/images/products/drinks/Lemon-Lime.webp',
    },
    {
      id: 'lemonade',
      category: 'drinks',
      name: 'Lemonade',
      image: '/images/products/drinks/Lemonade.webp',
    },
    {
      id: 'blackcurrant',
      category: 'drinks',
      name: 'Blackcurrant',
      image: '/images/products/drinks/Blackcurrant.webp',
    },
    {
      id: 'energy',
      category: 'drinks',
      name: 'Energy',
      image: '/images/products/drinks/Energy.webp',
    },
    {
      id: 'club-lemonade',
      category: 'drinks',
      name: 'Club Lemonade',
      image: '/images/products/drinks/Club-Lemonade.webp',
    },
  ],
  'tea': [
    {
      id: 'ketepa-pride',
      category: 'tea',
      name: 'Ketepa Pride',
      image: '/images/products/tea/Ketepa-Pride.png',
    },
    {
      id: 'safari-pure-tea',
      category: 'tea',
      name: 'Safari Pure Tea',
      image: '/images/products/tea/Safari-Pure-Tea.png',
    },
    {
      id: 'melvins-ginger-tea',
      category: 'tea',
      name: 'Melvins Ginger Tea',
      image: '/images/products/tea/Melvins-Ginger-Tea.webp',
    },
    {
      id: 'melvins-masala-tea',
      category: 'tea',
      name: 'Melvins Masala Tea',
      image: '/images/products/tea/Melvins-Masala-Tea.webp',
    },
    {
      id: 'fahari-black-tea',
      category: 'tea',
      name: 'Fahari Black Tea',
      image: '/images/products/tea/Fahari-Black-Tea.png',
    },
    {
      id: 'ginger-tea',
      category: 'tea',
      name: 'Ginger Tea',
      image: '/images/products/tea/Ginger-Tea.png',
    },
    {
      id: 'masala-tea',
      category: 'tea',
      name: 'Masala Tea',
      image: '/images/products/tea/Masala-Tea.png',
    },
    {
      id: 'lemon-green-tea',
      category: 'tea',
      name: 'Lemon Green Tea',
      image: '/images/products/tea/Lemon-Green-Tea.png',
    },
    {
      id: 'flavoured-hexagonal-pack',
      category: 'tea',
      name: 'Flavoured Hexagonal Pack',
      image: '/images/products/tea/Flavoured-Hexagonal-Pack.png',
    },
  ],
  'toilet-paper': [
    {
      id: 'velvex',
      category: 'toilet-paper',
      name: 'Velvex',
      image: '/images/products/toilet-paper/Velvex.png',
    },
    {
      id: 'nice-soft',
      category: 'toilet-paper',
      name: 'Nice & Soft',
      image: '/images/products/toilet-paper/Nice-Soft.png',
    },
    {
      id: 'toilex',
      category: 'toilet-paper',
      name: 'Toilex',
      image: '/images/products/toilet-paper/Toilex.png',
    },
    {
      id: 'rosy',
      category: 'toilet-paper',
      name: 'Rosy',
      image: '/images/products/toilet-paper/Rosy.png',
    },
  ],
  'pure-spices': [
    {
      id: 'black-pepper',
      category: 'pure-spices',
      name: 'Black Pepper',
      image: '/images/products/pure-spices/Black-Pepper.png',
    },
    {
      id: 'cardamoms',
      category: 'pure-spices',
      name: 'Cardamoms',
      image: '/images/products/pure-spices/Cardamoms.png',
    },
    {
      id: 'cayenne-pepper',
      category: 'pure-spices',
      name: 'Cayenne Pepper',
      image: '/images/products/pure-spices/Cayenne-Pepper.png',
    },
    {
      id: 'chilli-flakes',
      category: 'pure-spices',
      name: 'Chilli Flakes',
      image: '/images/products/pure-spices/Chilli-Flakes.png',
    },
    {
      id: 'chillies',
      category: 'pure-spices',
      name: 'Chillies',
      image: '/images/products/pure-spices/Chillies.png',
    },
    {
      id: 'cinnamon',
      category: 'pure-spices',
      name: 'Cinnamon',
      image: '/images/products/pure-spices/Cinnamon.png',
    },
    {
      id: 'cloves',
      category: 'pure-spices',
      name: 'Cloves',
      image: '/images/products/pure-spices/Cloves.png',
    },
    {
      id: 'coriander',
      category: 'pure-spices',
      name: 'Coriander',
      image: '/images/products/pure-spices/Coriander.png',
    },
    {
      id: 'cumin',
      category: 'pure-spices',
      name: 'Cumin',
      image: '/images/products/pure-spices/Cumin.png',
    },
    {
      id: 'garlic-powder',
      category: 'pure-spices',
      name: 'Garlic Powder',
      image: '/images/products/pure-spices/Garlic-Powder.png',
    },
    {
      id: 'ginger',
      category: 'pure-spices',
      name: 'Ginger',
      image: '/images/products/pure-spices/Ginger.png',
    },
    {
      id: 'nutmeg',
      category: 'pure-spices',
      name: 'Nutmeg',
      image: '/images/products/pure-spices/Nutmeg.png',
    },
    {
      id: 'onion-powder',
      category: 'pure-spices',
      name: 'Onion Powder',
      image: '/images/products/pure-spices/Onion-Powder.png',
    },
    {
      id: 'paprika',
      category: 'pure-spices',
      name: 'Paprika',
      image: '/images/products/pure-spices/Paprika.png',
    },
    {
      id: 'turmeric',
      category: 'pure-spices',
      name: 'Turmeric',
      image: '/images/products/pure-spices/Turmeric.png',
    },
    {
      id: 'white-pepper',
      category: 'pure-spices',
      name: 'White Pepper',
      image: '/images/products/pure-spices/White-Pepper.png',
    },
  ],
  'seasonings': [
    {
      id: 'biryani-masala',
      category: 'seasonings',
      name: 'Biryani Masala',
      image: '/images/products/seasonings/Biryani-Masala.png',
    },
    {
      id: 'chilli-lemon',
      category: 'seasonings',
      name: 'Chilli Lemon',
      image: '/images/products/seasonings/Chilli-Lemon.png',
    },
    {
      id: 'dhana-jeera',
      category: 'seasonings',
      name: 'Dhana Jeera',
      image: '/images/products/seasonings/Dhana-Jeera.png',
    },
    {
      id: 'garam-masala',
      category: 'seasonings',
      name: 'Garam Masala',
      image: '/images/products/seasonings/Garam-Masala.png',
    },
    {
      id: 'mixed-spices',
      category: 'seasonings',
      name: 'Mixed Spices',
      image: '/images/products/seasonings/Mixed-Spices.png',
    },
    {
      id: 'mixed-spices-for-wet-and-dry',
      category: 'seasonings',
      name: 'Mixed Spices for Wet and Dry',
      image: '/images/products/seasonings/Mixed-Spices-for-Wet-and-Dry.png',
    },
    {
      id: 'peri-peri',
      category: 'seasonings',
      name: 'Peri Peri',
      image: '/images/products/seasonings/Peri-Peri.png',
    },
    {
      id: 'pilau-masala',
      category: 'seasonings',
      name: 'Pilau Masala',
      image: '/images/products/seasonings/Pilau-Masala.png',
    },
    {
      id: 'salad-seasoning',
      category: 'seasonings',
      name: 'Salad Seasoning',
      image: '/images/products/seasonings/Salad-Seasoning.png',
    },
    {
      id: 'tea-masala',
      category: 'seasonings',
      name: 'Tea Masala',
      image: '/images/products/seasonings/Tea-Masala.png',
    }
  ],
  'salts': [
    {
      id: 'citric-acid',
      category: 'salts',
      name: 'Citric Acid',
      image: '/images/products/salts/Citric-Acid.png',
    },
    {
      id: 'meat-tenderiser',
      category: 'salts',
      name: 'Meat Tenderiser',
      image: '/images/products/salts/Meat-Tenderizer.png',
    },
  ],
  'herbs': [
    {
      id: 'basil',
      category: 'herbs',
      name: 'Basil',
      image: '/images/products/herbs/Basil.png',
    },
    {
      id: 'bay-leaves',
      category: 'herbs',
      name: 'Bay Leaves',
      image: '/images/products/herbs/Bay-Leaves.png',
    },
    {
      id: 'marjoram',
      category: 'herbs',
      name: 'Marjoram',
      image: '/images/products/herbs/Marjoram.png',
    },
    {
      id: 'mint',
      category: 'herbs',
      name: 'Mint',
      image: '/images/products/herbs/Mint.png',
    },
    {
      id: 'mixed-herbs',
      category: 'herbs',
      name: 'Mixed Herbs',
      image: '/images/products/herbs/Mixed-Herbs.png',
    },
    {
      id: 'oregano',
      category: 'herbs',
      name: 'Oregano',
      image: '/images/products/herbs/Oregano.png',
    },
    {
      id: 'parsley',
      category: 'herbs',
      name: 'Parsley',
      image: '/images/products/herbs/Parsley.png',
    },
    {
      id: 'rosemary-leaves',
      category: 'herbs',
      name: 'Rosemary Leaves',
      image: '/images/products/herbs/Rosemary-Leaves.png',
    },
    {
      id: 'sage',
      category: 'herbs',
      name: 'Sage',
      image: '/images/products/herbs/Sage.png',
    },
    {
      id: 'thyme',
      category: 'herbs',
      name: 'Thyme',
      image: '/images/products/herbs/Thyme.png',
    },
  ],
  'masalas': [
    {
      id: 'beef-masala',
      category: 'masalas',
      name: 'Beef Masala',
      image: '/images/products/masalas/Beef-Masala.png',
    },
    {
      id: 'chicken-masala',
      category: 'masalas',
      name: 'Chicken Masala',
      image: '/images/products/masalas/Chicken-Masala.png',
    },
    {
      id: 'chips-masala',
      category: 'masalas',
      name: 'Chips Masala',
      image: '/images/products/masalas/Chips-Masala.png',
    },
    {
      id: 'curry-powder',
      category: 'masalas',
      name: 'Curry Powder',
      image: '/images/products/masalas/Curry-Powder.png',
    },
    {
      id: 'fish-masala',
      category: 'masalas',
      name: 'Fish Masala',
      image: '/images/products/masalas/Fish-Masala.png',
    },
    {
      id: 'githeri-masala',
      category: 'masalas',
      name: 'Githeri Masala',
      image: '/images/products/masalas/Githeri-Masala.png',
    },
  ],
  'grinders': [
    {
      id: 'black-peppercorn',
      category: 'grinders',
      name: 'Black Peppercorn',
      image: '/images/products/grinders/Black-Peppercorn.png',
    },
    {
      id: 'fireball',
      category: 'grinders',
      name: 'Fireball',
      image: '/images/products/grinders/Fireball.png',
    },
    {
      id: 'himalayan-pink-salt',
      category: 'grinders',
      name: 'Himalayan Pink Salt',
      image: '/images/products/grinders/Himalayan-Pink-Salt.png',
    },
    {
      id: 'mixed-spice-whole',
      category: 'grinders',
      name: 'Mixed Spice Whole',
      image: '/images/products/grinders/Mixed-Spice-Whole.png',
    },
    {
      id: 'pepper-medley-whole',
      category: 'grinders',
      name: 'Pepper Medley Whole',
      image: '/images/products/grinders/Pepper-Medley-Whole.png',
    },
    {
      id: 'sea-salt-whole',
      category: 'grinders',
      name: 'Sea Salt Whole',
      image: '/images/products/grinders/Sea-Salt-Whole.png',
    },
  ],
  'pops': [
    {
      id: 'popped-nachos-salted',
      category: 'pops',
      name: 'Popped Nachos Salted',
      image: '/images/products/pops/Popped-Nachos-Salted.png',
    },
    {
      id: 'popped-nachos-tomato',
      category: 'pops',
      name: 'Popped Nachos Tomato',
      image: '/images/products/pops/Popped-Nachos-Tomato.png',
    },
    {
      id: 'popped-nachos-cheese',
      category: 'pops',
      name: 'Popped Nachos Cheese',
      image: '/images/products/pops/Popped-Nachos-Cheese.png',
    },
    {
      id: 'popped-nachos-chilli-lime',
      category: 'pops',
      name: 'Popped Nachos Chilli Lime',
      image: '/images/products/pops/Popped-Nachos-Chilli-Lime.png',
    },
  ],
  'banana-crips': [
    {
      id: 'salted',
      category: 'banana-crips',
      name: 'Salted',
      image: '/images/products/banana-crips/Banana-Crips-Salted.png',
    },
    {
      id: 'chilli-lemon',
      category: 'banana-crips',
      name: 'Chilli Lemon',
      image: '/images/products/banana-crips/Banana-Crips-Chilli-Lemon.png',
    },
    {
      id: 'chilli-salted',
      category: 'banana-crips',
      name: 'Chilli Salted',
      image: '/images/products/banana-crips/Banana-Crips-Chilli-Salted.png',
    },
  ],
  'heroes': [
    {
      id: 'chilli-cheese',
      category: 'heroes',
      name: 'Chilli Cheese',
      image: '/images/products/heroes/Chilli-Cheese.png',
    },
    {
      id: 'salted',
      category: 'heroes',
      name: 'Salted',
      image: '/images/products/heroes/Classic-Salted.png',
    },
    {
      id: 'sweet-chilli',
      category: 'heroes',
      name: 'Sweet Chilli',
      image: '/images/products/heroes/Sweet-Chilli.png',
    },
    {
      id: 'fruit-chutney',
      category: 'heroes',
      name: 'Fruit Chutney',
      image: '/images/products/heroes/Fruit-Chutney.png',
    },
    {
      id: 'salt-and-vinegar',
      category: 'heroes',
      name: 'Salt & Vinegar',
      image: '/images/products/heroes/Salt-and-Vinegar.png',
    },
    {
      id: 'cheese-and-onion',
      category: 'heroes',
      name: 'Cheese & Onion',
      image: '/images/products/heroes/Cheese-and-Onion.png',
    },
    {
      id: 'tomato-ketchup',
      category: 'heroes',
      name: 'Tomato Ketchup',
      image: '/images/products/heroes/Tomato-Ketchup.png',
    },
  ],
  'waves': [
    {
      id: 'fruit-chutney',
      category: 'waves',
      name: 'Fruit Chutney',
      image: '/images/products/waves/Fruit-Chutney.png',
    },
    {
      id: 'salted',
      category: 'waves',
      name: 'Salted',
      image: '/images/products/waves/Salted.png',
    },
    {
      id: 'salt-and-vinegar',
      category: 'waves',
      name: 'Salt & Vinegar',
      image: '/images/products/waves/Salt-and-Vinegar.png',
    },
    {
      id: 'chilli-lemon',
      category: 'waves',
      name: 'Chilli Lemon',
      image: '/images/products/waves/Chilli-Lemon.png',
    },
    {
      id: 'tomato',
      category: 'waves',
      name: 'Tomato',
      image: '/images/products/waves/Tomato.png',
    },
  ],
  'potato-crisps': [
    {
      id: 'sweet-paprika',
      category: 'potato-crisps',
      name: 'Sweet Paprika',
      image: '/images/products/potato-crisps/Sweet-Paprika.png',
    },
    {
      id: 'salted',
      category: 'potato-crisps',
      name: 'Salted',
      image: '/images/products/potato-crisps/Salted.png',
    },
    {
      id: 'cheese-and-onion',
      category: 'potato-crisps',
      name: 'Cheese & Onion',
      image: '/images/products/potato-crisps/Cheese-and-Onion.png',
    },
    {
      id: 'salt-and-vinegar',
      category: 'potato-crisps',
      name: 'Salt & Vinegar',
      image: '/images/products/potato-crisps/Salt-and-Vinegar.png',
    },
    {
      id: 'chilli-lemon',
      category: 'potato-crisps',
      name: 'Chilli Lemon',
      image: '/images/products/potato-crisps/Chilli-Lemon.png',
    },
    {
      id: 'tomato',
      category: 'potato-crisps',
      name: 'Tomato',
      image: '/images/products/potato-crisps/Tomato.png',
    },
    {
      id: 'nyama-choma',
      category: 'potato-crisps',
      name: 'Nyama Choma',
      image: '/images/products/potato-crisps/Nyama-Choma.png',
    },
    {
      id: 'masala-sticks',
      category: 'potato-crisps',
      name: 'Masala Sticks',
      image: '/images/products/potato-crisps/Masala-Sticks.png',
    },
  ],
  'tropnuts': [
    {
      id: 'masala-bhajia-peanuts',
      category: 'tropnuts',
      name: 'Masala Bhajia Peanuts',
      image: '/images/products/tropnuts/Masala-Bhajia-Peanuts.png',
    },
    {
      id: 'fried-peanuts',
      category: 'tropnuts',
      name: 'Fried Peanuts',
      image: '/images/products/tropnuts/Fried-Peanuts.png',
    },
    {
      id: 'chilli-lemon-peanuts',
      category: 'tropnuts',
      name: 'Chilli Lemon Peanuts',
      image: '/images/products/tropnuts/Chilli-Lemon-Peanuts.png',
    },
    {
      id: 'roasted-salted-peanuts',
      category: 'tropnuts',
      name: 'Roasted Salted Peanuts',
      image: '/images/products/tropnuts/Roasted-Salted-Peanuts.png',
    },
    {
      id: 'fried-peas',
      category: 'tropnuts',
      name: 'Fried Peas',
      image: '/images/products/tropnuts/Fried-Peas.png',
    },
    {
      id: 'roasted-peanuts',
      category: 'tropnuts',
      name: 'Roasted Peanuts',
      image: '/images/products/tropnuts/Roasted-Peanuts.png',
    },
    {
      id: 'exotic-nut-mix',
      category: 'tropnuts',
      name: 'Exotic Nut Mix',
      image: '/images/products/tropnuts/Exotic-Nut-Mix.png',
    },
  ],
  'ethnic-snacks': [
    {
      id: 'chevda-original',
      category: 'ethnic-snacks',
      name: 'Chevda Original',
      image: '/images/products/ethnic-snacks/Chevda-Original.png',
    },
    {
      id: 'chevda-hot',
      category: 'ethnic-snacks',
      name: 'Chevda Hot',
      image: '/images/products/ethnic-snacks/Chevda-Hot.png',
    },
    {
      id: 'chevda-chilli-lemon',
      category: 'ethnic-snacks',
      name: 'Chevda Chilli Lemon',
      image: '/images/products/ethnic-snacks/Chevda-Chilli-Lemon.png',
    },
    {
      id: 'chevda-no-sugar-added',
      category: 'ethnic-snacks',
      name: 'Chevda No Sugar Added',
      image: '/images/products/ethnic-snacks/Chevda-No-Sugar-Added.png',
    },
    {
      id: 'chevda-masala',
      category: 'ethnic-snacks',
      name: 'Chevda Masala',
      image: '/images/products/ethnic-snacks/Chevda-Masala.png',
    },
    {
      id: 'chevda-mild',
      category: 'ethnic-snacks',
      name: 'Chevda Mild',
      image: '/images/products/ethnic-snacks/Chevda-Mild.png',
    },
    {
      id: 'chevda-sweet-tamu',
      category: 'ethnic-snacks',
      name: 'Chevda Sweet Tamu',
      image: '/images/products/ethnic-snacks/Chevda-Sweet-Tamu.png',
    },
    {
      id: 'nairobi-mix-bhusu',
      category: 'ethnic-snacks',
      name: 'Nairobi Mix Bhusu',
      image: '/images/products/ethnic-snacks/Nairobi-Mix-Bhusu.png',
    },
  ],
  'safari-puffs': [
    {
      id: 'chilli-lemon',
      category: 'safari-puffs',
      name: 'Chilli Lemon',
      image: '/images/products/safari-puffs/Chilli-Lemon.png',
    },
    {
      id: 'cheese',
      category: 'safari-puffs',
      name: 'Cheese',
      image: '/images/products/safari-puffs/Cheese.png',
    },
    {
      id: 'tomato',
      category: 'safari-puffs',
      name: 'Tomato',
      image: '/images/products/safari-puffs/Tomato.png',
    },
    {
      id: 'barbeque',
      category: 'safari-puffs',
      name: 'Barbeque',
      image: '/images/products/safari-puffs/Barbeque.png',
    },
  ],
  'rice-cakes': [
    {
      id: 'chocolate-rice-cakes',
      category: 'rice-cakes',
      name: 'Chocolate Rice Cakes',
      image: '/images/products/rice-cakes/Chocolate-Rice-Cakes.png',
    },
    {
      id: 'rice-cakes-unsalted',
      category: 'rice-cakes',
      name: 'Rice Cakes Unsalted',
      image: '/images/products/rice-cakes/Rice-Cakes-Unsalted.png',
    },
    {
      id: 'rice-cakes-salted',
      category: 'rice-cakes',
      name: 'Rice Cakes Salted',
      image: '/images/products/rice-cakes/Rice-Cakes-Salted.png',
    },
    {
      id: 'rice-cakes-brown-rice',
      category: 'rice-cakes',
      name: 'Rice Cakes Brown Rice',
      image: '/images/products/rice-cakes/Rice-Cakes-Brown-Rice.png',
    },
    {
      id: 'rice-cakes-salt-and-vinegar',
      category: 'rice-cakes',
      name: 'Rice Cakes Salt & Vinegar',
      image: '/images/products/rice-cakes/Rice-Cakes-Salt-and-Vinegar.png',
    },
    {
      id: 'rice-cakes-cheese',
      category: 'rice-cakes',
      name: 'Rice Cakes Cheese',
      image: '/images/products/rice-cakes/Rice-Cakes-Cheese.png',
    },
    {
      id: 'rice-cakes-fruit-chutney',
      category: 'rice-cakes',
      name: 'Rice Cakes Fruit Chutney',
      image: '/images/products/rice-cakes/Rice-Cakes-Fruit-Chutney.png',
    },
  ],
};

export const categoryTitles: CategoryTitle = {
  'cooking-oil': 'Cooking Oil/Fat',
  'soaps-self-care': 'Self-Care Soaps',
  'wash-day-soaps': 'Wash Day Soaps',
  'sauces': 'Sauces',
  'condiments': 'Condiments',
  'powders': 'Powders',
  'vinegar': 'Vinegar',
  'jams': 'Jams',
  'canned-food': 'Canned Food',
  'choco-drinks': 'Chocolate Drinks',
  'rice': 'Rice',
  'sweets': 'Sweets',
  'drinks': 'Drinks',
  'tea': 'Tea',
  'toilet-paper': 'Toilet Paper',
  'pure-spices': 'Pure Spices',
  'seasonings': 'Seasonings',
  'salts': 'Salts',
  'herbs': 'Herbs',
  'masalas': 'Masalas',
  'grinders': 'Grinders',
  'pops': 'Pops',
  'banana-crips': 'Banana Crips',
  'heroes': 'Heroes',
  'waves': 'Waves',
  'potato-crisps': 'Potato Crisps',
  'tropnuts': 'Tropnuts',
  'ethnic-snacks': 'Ethnic Snacks',
  'safari-puffs': 'Safari Puffs',
  'rice-cakes': 'Rice Cakes',
};
